name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa a cada dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório do Snake
      - name: Baixar código do Snake
        uses: actions/checkout@v3

      # Configura e executa o Snake
      - name: Configurar Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      # Faz upload do arquivo gerado para o GitHub Pages
      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
